services:
  ai_server:
    container_name: ai_server
    build:
      context: ./AI
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    restart: always

  be_server:
    container_name: be_server
    build:
      context: ./BE
    ports:
      - "3000:3000"
    environment:
      - AI_URL=http://ai_server:8000
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - be_db:/app/prisma
    depends_on:
      - ai_server
    command: >
      sh -c "npx prisma migrate deploy && npx prisma db seed && node src/index.js"
    restart: always

volumes:
  be_db:
